### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by floriancargoet** [floriancargoet/quixe-plus#1]
- [ ] README
  - [ ] Installation
  - [ ] Map usage
  - [ ] Query usage
  - [ ] Globals I6 / I7
- [ ] Write tests
  - [ ] Auto compile stories
  - [ ] Explore generating stories on the fly
  - [ ] Explore generating a JSDOM env per `withStory()` (instead of per test file)
- [ ] Better selectors
  - [ ] Multiple attributes `".door.locked"`
  - [ ] Combine name & attributes `"trapdoor.closed"`
  - [ ] Explore if selection by kind is possible (class is in property "inheritance class" but class values in gameinfo are > endmem)
- [ ] Maps
  - [ ] Tiled map
  - [ ] 3D map?
- [ ] Template
  - [ ] responsive layout
  - [ ] keep sidebar?
